### ISSUE TITLE
Make the tutorial start bigger

### ISSUE THREAD

**Issue by AlexanderLanin** [anoff/devradar#134]
Hi,

i just opened the page for the first time, logged in via github and was wondering why it's all empty. I have a 34" monitor and opened the page on the whole screen. It scales.
After a while I found a really small box saying "Create a new skill entry".
It's all fine when you make the browser smaller, but when it's so big... I did not notice there even is a button at the bottom.

**Comment by anoff** [comment]
Hey @AlexanderLanin thanks for the info. I will see what I can do to make it better visible.
Would changing colors also help or is it mainly scaling the boxes?

Just out of curiousity; did you have any problems figuring out how to start the tutorial?

**Comment by anoff** [comment]
Increased box + text size.
 
Here's a preview: https://preview.devradar.io/#/
Auth does not work though, because I couldn't figure out if/how to re-use the existing auth providers for a secondary URL.

But the first tutorial stage should give you an idea. How does the size look on your screen?
