### ISSUE TITLE
"Veteran" in personal radar does not match to "Expert" in link

### ISSUE THREAD

**Issue by md42** [anoff/devradar#49]
in https://github.com/anoff/devradar/tree/master/editor#personal-devradar highest State is "Veteran" but linked https://hr.nih.gov/working-nih/competencies/competencies-proficiency-scale states highest level is "Expert". Realy small issue, just shortly confuses when words don't align, was questioning if i should raise it. I am also fine with won't fix.

**Comment by anoff** [comment]
thanks, fixed in the markdown and website
